# Generated by Django 5.1.3 on 2024-12-23 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='create_ad',
            new_name='create_at',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='parent_comment_id',
            new_name='parent_comment',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='user',
        ),
    ]
