# Generated by Django 5.1.3 on 2024-12-24 23:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('likes', '0002_remove_like_id_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='target_id',
        ),
        migrations.RemoveField(
            model_name='like',
            name='target_type',
        ),
        migrations.AddField(
            model_name='like',
            name='content_type',
            field=models.ForeignKey(default='post', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='like',
            name='object_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
